[config]
default_to_workspace = false

[env]
DOTNET_VERSION = "netcoreapp3.1"
DOTNET_CONFIG = "Debug"
CORECLR_ENABLE_PROFILING = { value = "1", condition = { env_not_set = ["CORECLR_ENABLE_PROFILING"] } }
CORECLR_PROFILER = { value = "{FA65FE15-F085-4681-9B20-95E04F6C03CC}", condition = { env_not_set = ["CORECLR_PROFILER"] } }
ELASTIC_APM_PROFILER_HOME = { value = "${CARGO_MAKE_WORKING_DIRECTORY}/src/Elastic.Apm.Profiler.Managed/bin/Release", condition = { env_not_set = ["ELASTIC_APM_PROFILER_HOME"] } }
ELASTIC_APM_PROFILER_INTEGRATIONS = { value = "${CARGO_MAKE_WORKING_DIRECTORY}/src/Elastic.Apm.Profiler.Managed/integrations.yml", condition = { env_not_set = ["ELASTIC_APM_PROFILER_INTEGRATIONS"] } }
ELASTIC_APM_PROFILER_CALLTARGET_ENABLED = { value = "true", condition = { env_not_set = ["ELASTIC_APM_PROFILER_CALLTARGET_ENABLED"] } }
ELASTIC_APM_PROFILER_LOG = { value = "debug", condition = { env_not_set = ["ELASTIC_APM_PROFILER_LOG"] } }
ELASTIC_APM_PROFILER_LOG_IL = { value = "true", condition = { env_not_set = ["ELASTIC_APM_PROFILER_LOG_IL"] } }
ELASTIC_APM_PROFILER_LOG_DIR = { value = "logs", condition = { env_not_set = ["ELASTIC_APM_PROFILER_LOG_DIR"] } }
ELASTIC_APM_PROFILER_LOG_TARGETS = { value = "file,stdout", condition = { env_not_set = ["ELASTIC_APM_PROFILER_LOG_TARGETS"] } }

[tasks.build-loader]
description = "Builds Managed Profiler .NET loader"
command = "dotnet"
args = ["build", "-c", "Release", "./src/Elastic.Apm.Profiler.Managed.Loader/Elastic.Apm.Profiler.Managed.Loader.csproj"]

[tasks.build]
description = "Builds CLR Profiler"
# loader assembly is embedded in the profiler
dependencies = ["build-loader"]

[tasks.build-release]
description = "Builds CLR Profiler for release"
# loader assembly is embedded in the profiler
dependencies = ["build-loader"]

[tasks.build-integrations]
description = "Builds Managed Profiler .NET integrations"
command = "dotnet"
args = ["build", "-c", "Release", "./src/Elastic.Apm.Profiler.Managed/Elastic.Apm.Profiler.Managed.csproj"]

[tasks.build-example]
description = "Builds Example .NET project to instrument"
command = "dotnet"
args = ["build", "-c", "${DOTNET_CONFIG}", "./sample/Example/Example.csproj"]

[tasks.generate-integrations]
description = "Generates integrations files from Managed Profiler assembly"
dependencies = ["generate-integrations-json", "generate-integrations-yml"]

[tasks.generate-integrations-json]
description = "Generates integrations.json file"
command = "dotnet"
args = [
    "run",
    "--project", "./src/Elastic.Apm.Profiler.IntegrationsGenerator/Elastic.Apm.Profiler.IntegrationsGenerator.csproj",
    "--",
    "-i", "./src/Elastic.Apm.Profiler.Managed/bin/Release/netstandard2.0/Elastic.Apm.Profiler.Managed.dll",
    "-o", "./src/Elastic.Apm.Profiler.Managed",
    "-f", "json"]
dependencies = ["build-integrations"]

[tasks.generate-integrations-yml]
description = "Generates integrations.json file"
command = "dotnet"
args = [
    "run",
    "--project", "./src/Elastic.Apm.Profiler.IntegrationsGenerator/Elastic.Apm.Profiler.IntegrationsGenerator.csproj",
    "--",
    "-i", "./src/Elastic.Apm.Profiler.Managed/bin/Release/netstandard2.0/Elastic.Apm.Profiler.Managed.dll",
    "-o", "./src/Elastic.Apm.Profiler.Managed",
    "-f", "yml"]
dependencies = ["build-integrations"]

[tasks.expand]
clear = true
script = '''
cargo expand --manifest-path src/elastic_apm_profiler/Cargo.toml --color never > expanded.rs
'''

[tasks.set-profiler-env]
private = true
env = { "CORECLR_PROFILER_PATH" = "${CARGO_MAKE_WORKING_DIRECTORY}/target/debug/libelastic_apm_profiler.so" }

[tasks.set-profiler-env.mac]
env = { "CORECLR_PROFILER_PATH" = "${CARGO_MAKE_WORKING_DIRECTORY}/target/debug/libelastic_apm_profiler.dylib" }

[tasks.set-profiler-env.windows]
env = { "CORECLR_PROFILER_PATH" = "${CARGO_MAKE_WORKING_DIRECTORY}\\target\\debug\\elastic_apm_profiler.dll" }

[tasks.run-dotnet]
command = "dotnet"
args = ["${CARGO_MAKE_WORKING_DIRECTORY}/sample/Example/bin/${DOTNET_CONFIG}/${DOTNET_VERSION}/Example.dll"]
dependencies = ["set-profiler-env"]

[tasks.test]
dependencies = ["generate-integrations"]

[tasks.test-example]
clear = true
dependencies = ["build-release", "generate-integrations", "build-example", "run-dotnet"]